import BottomBar from "@/components/BottomBar";
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "Next Booking",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="relative mx-auto max-w-screen-sm">
        <Navbar />
        <main className="scrollbar-none min-h-[calc(100dvh-126px)] overflow-hidden overflow-y-scroll">
          {children}
        </main>
        <BottomBar />
      </body>
    </html>
  );
}
