import BottomBar from "@/components/BottomBar";
import Navbar from "@/components/Navbar";
import "@/styles/globals.css";

export const metadata = {
  title: "Next Booking",
  description: "Generated by Next.js",
};

interface RootLayoutProps {
  children: React.ReactNode;
}

export default function RootLayout({ children }: RootLayoutProps) {
  return (
    <html lang="en">
      <body className="relative max-w-screen-sm mx-auto px-8 md:px-0">
        <header className="sticky top-0 bg-white z-[999]">
          <Navbar />
        </header>
        <main className="min-h-[calc(100dvh-153px)] overflow-hidden overflow-y-scroll no-scrollbar">
          {children}
        </main>
        <footer className="sticky bottom-0 bg-white w-full">
          <BottomBar />
        </footer>
      </body>
    </html>
  );
}
